export const EVE_BEZIER_CURVINESS_DEFAULT = 150;
export const EVE_BEZIER_CURVINESS_MIN = -2500;
export const EVE_BEZIER_CURVINESS_MAX = 2500;
export const EVE_BEZIER_CURVINESS_STEP = 1;

export const EVE_STATE_MACHINE_CURVINESS_DEFAULT = 0;
export const EVE_STATE_MACHINE_CURVINESS_MIN = -2500;
export const EVE_STATE_MACHINE_CURVINESS_MAX = 2500;
export const EVE_STATE_MACHINE_CURVINESS_STEP = 1;

export const EVE_FLOWCHART_ROUNDNESS_DEFAULT = 0;
export const EVE_FLOWCHART_ROUNDNESS_MIN = -250;
export const EVE_FLOWCHART_ROUNDNESS_MAX = 250;
export const EVE_FLOWCHART_ROUNDNESS_STEP = 1;
