import { CustomAdapter } from '../qemu/qemu-custom-adapter';

export class QemuTemplate {
  adapter_type: string;
  adapters: number;
  bios_image: string;
  boot_priority: string;
  builtin: boolean;
  category: string;
  cdrom_image: string;
  compute_id: string;
  console_auto_start: boolean;
  console_type: string;
  cpu_throttling: number;
  cpus: number;
  custom_adapters: CustomAdapter[];
  default_name_format: string;
  first_port_name: string;
  hda_disk_image: string;
  hda_disk_interface: string;
  hdb_disk_image: string;
  hdb_disk_interface: string;
  hdc_disk_image: string;
  hdc_disk_interface: string;
  hdd_disk_image: string;
  hdd_disk_interface: string;
  initrd: string;
  kernel_command_line: string;
  kernel_image: string;
  linked_clone: boolean;
  mac_address: string;
  name: string;
  on_close: string;
  options: string;
  platform: string;
  port_name_format: string;
  port_segment_size: number;
  process_priority: string;
  qemu_path: string;
  ram: number;
  symbol: string;
  template_id: string;
  template_type: string;
  usage: string;
}
