// Runtime enrichment of the compiled SETTINGS_METADATA from the server's
// OpenAPI document (GET /openapi.json, served at the application root). The
// document is generated by the server at startup, so its field descriptions,
// builtin defaults, numeric bounds and enum choices always match the server
// version — the parts of the metadata most likely to drift. Grouping, field
// order, labels, layout widths and restart flags are UI decisions and stay in
// the compiled metadata. Everything here is best-effort: a missing document,
// section or field leaves the compiled value untouched.

import { ServerSettingsSectionName } from './server-settings';
import { SETTINGS_METADATA, SettingsFieldMeta, SettingsSectionMeta } from './settings-metadata';

// The OpenAPI document is only read, never written; a full spec typing would
// buy nothing, so just the parts we walk are declared.
export interface OpenApiSchemaObject {
  type?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  format?: string;
  $ref?: string;
  items?: OpenApiSchemaObject;
  anyOf?: OpenApiSchemaObject[];
  properties?: { [name: string]: OpenApiSchemaObject };
}

export interface OpenApiDocument {
  components?: { schemas?: { [name: string]: OpenApiSchemaObject } };
}

// Per section, the resolved schema of every field the server knows about.
export type SettingsSectionSchemas = {
  [K in ServerSettingsSectionName]?: { [field: string]: OpenApiSchemaObject };
};

const REF_PATTERN = /^#\/components\/schemas\/(.+)$/;

function resolveRef(schemas: { [name: string]: OpenApiSchemaObject }, ref: string): OpenApiSchemaObject | undefined {
  const match = REF_PATTERN.exec(ref);
  return match ? schemas[match[1]] : undefined;
}

// Pull the schema of each section's fields out of the document by following
// SettingsResponse → section $ref → properties. Section component names are
// not uniform (ServerSettingsResponse vs VPCSSettings), so discovery goes
// through the references rather than name patterns. Returns null when the
// document has no SettingsResponse (older servers) — callers fall back to the
// compiled metadata.
export function extractSettingsSchemas(openapi: OpenApiDocument): SettingsSectionSchemas | null {
  const schemas = openapi?.components?.schemas;
  const sectionRefs = schemas?.['SettingsResponse']?.properties;
  if (!schemas || !sectionRefs) {
    return null;
  }

  const result: SettingsSectionSchemas = {};
  for (const section of SETTINGS_METADATA) {
    const ref = sectionRefs[section.name]?.$ref;
    const properties = ref ? resolveRef(schemas, ref)?.properties : undefined;
    if (properties) {
      result[section.name] = inlineEnumRefs(properties, schemas);
    }
  }
  return Object.keys(result).length ? result : null;
}

// FastAPI keeps description/default on the referring property but moves the
// enum choices into the referenced component. Inline the enum here, while the
// component registry is still at hand, so enrichment needs no $ref hops.
function inlineEnumRefs(
  properties: { [name: string]: OpenApiSchemaObject },
  schemas: { [name: string]: OpenApiSchemaObject }
): { [field: string]: OpenApiSchemaObject } {
  const inlined: { [field: string]: OpenApiSchemaObject } = {};
  for (const [key, spec] of Object.entries(properties)) {
    const resolved = spec.$ref ? resolveRef(schemas, spec.$ref) : undefined;
    if (!resolved?.enum) {
      inlined[key] = spec;
      continue;
    }
    const copy: OpenApiSchemaObject = { ...spec, enum: resolved.enum };
    delete copy.$ref;
    inlined[key] = copy;
  }
  return inlined;
}

export function enrichSettingsMetadata(
  metadata: SettingsSectionMeta[],
  schemas: SettingsSectionSchemas
): SettingsSectionMeta[] {
  return metadata.map((section) => {
    const fieldSchemas = schemas[section.name];
    if (!fieldSchemas) {
      return section;
    }
    return {
      ...section,
      groups: section.groups.map((group) => ({
        ...group,
        fields: group.fields.map((field) => enrichField(field, fieldSchemas[field.key])),
      })),
    };
  });
}

function enrichField(field: SettingsFieldMeta, spec: OpenApiSchemaObject | undefined): SettingsFieldMeta {
  if (!spec) {
    return field;
  }

  const next: SettingsFieldMeta = { ...field };
  if (spec.description) {
    next.hint = spec.description;
  }

  const min = lowerBound(spec);
  const max = upperBound(spec);
  if (min !== undefined) {
    next.min = min;
  }
  if (max !== undefined) {
    next.max = max;
  }

  const enumValues = readEnum(spec);
  if (enumValues) {
    next.options = enumValues.map((value) => ({
      value,
      label: field.options?.find((option) => option.value === value)?.label ?? prettifyEnumValue(value),
    }));
  }

  // Only refine defaults the compiled metadata already declares. Schema
  // defaults can carry runtime state — the hostname-derived server name, the
  // masked admin password — and adopting those would turn "reset to default"
  // into "write the current value into the config file". Secrets never take
  // schema defaults for the same reason.
  const defaultValue = readDefault(spec);
  if (field.defaultValue !== undefined && field.type !== 'secret' && defaultValue !== undefined) {
    next.defaultValue = defaultValue;
  }

  return next;
}

// Pydantic's gt/lt surface as exclusiveMinimum/exclusiveMaximum. Our numeric
// fields are integers, where "greater than 0" means "at least 1" — enough for
// the HTML min/max attributes and the save-time clamp.
function lowerBound(spec: OpenApiSchemaObject): number | undefined {
  if (typeof spec.minimum === 'number') {
    return spec.minimum;
  }
  if (typeof spec.exclusiveMinimum === 'number') {
    return spec.exclusiveMinimum + 1;
  }
  return undefined;
}

function upperBound(spec: OpenApiSchemaObject): number | undefined {
  if (typeof spec.maximum === 'number') {
    return spec.maximum;
  }
  if (typeof spec.exclusiveMaximum === 'number') {
    return spec.exclusiveMaximum - 1;
  }
  return undefined;
}

// FastAPI puts enums in a sibling component and keeps description/default on
// the referring property; extractSettingsSchemas inlines the choices already.
function readEnum(spec: OpenApiSchemaObject): string[] | null {
  const values = spec.enum;
  if (Array.isArray(values) && values.every((value) => typeof value === 'string')) {
    return values;
  }
  return null;
}

function prettifyEnumValue(value: string): string {
  return value
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function readDefault(spec: OpenApiSchemaObject): SettingsFieldMeta['defaultValue'] {
  const value = spec.default;
  if (typeof value === 'boolean' || typeof value === 'number' || typeof value === 'string') {
    return value;
  }
  if (Array.isArray(value) && value.every((item) => typeof item === 'string')) {
    return value;
  }
  return undefined; // absent or null — no information, keep the compiled value
}
