export type DockerIpv4Mode = 'dhcp' | 'static' | 'manual';
export type DockerIpv6Mode = 'disabled' | 'auto' | 'dhcp' | 'static' | 'manual';

export interface DockerNetworkInterface {
  name: string;
  enabled: boolean;
  startupKeyword: 'auto' | 'allow-hotplug';
  ipv4Mode: DockerIpv4Mode;
  ipv4Address: string;
  netmask: string;
  ipv4Gateway: string;
  hostname: string;
  dnsNameservers: string;
  mtu: string;
  ipv6Mode: DockerIpv6Mode;
  ipv6Address: string;
  prefixLength: string;
  ipv6Gateway: string;
  ipv4ExtraDirectives: string[];
  ipv6ExtraDirectives: string[];
}

export interface ParsedDockerNetworkConfiguration {
  interfaces: DockerNetworkInterface[];
  preservedConfiguration: string;
}

const INTERFACE_NAME_PATTERN = /^eth(\d+)$/;
const COMMENTED_TEMPLATE_HEADER_PATTERN = /^#\s*(?:static|dhcp)\s+config\s+for\s+eth\d+\s*$/i;
const COMMENTED_STARTUP_PATTERN = /^#\s*(auto|allow-hotplug)\s+(.+?)\s*$/;
const COMMENTED_STANZA_PATTERN = /^#\s*iface\s+(eth\d+)\s+inet6?\s+\S+\s*$/;
const COMMENTED_DIRECTIVE_PATTERN =
  /^#\s*(?:address|netmask|gateway|hostname|dns-nameservers|mtu|up|down|pre-up|post-up|pre-down|post-down)\b/;

function createInterface(name: string): DockerNetworkInterface {
  return {
    name,
    enabled: false,
    startupKeyword: 'auto',
    ipv4Mode: 'dhcp',
    ipv4Address: '',
    netmask: '255.255.255.0',
    ipv4Gateway: '',
    hostname: '',
    dnsNameservers: '',
    mtu: '',
    ipv6Mode: 'disabled',
    ipv6Address: '',
    prefixLength: '64',
    ipv6Gateway: '',
    ipv4ExtraDirectives: [],
    ipv6ExtraDirectives: [],
  };
}

function interfaceNumber(name: string): number {
  return Number(INTERFACE_NAME_PATTERN.exec(name)?.[1] ?? Number.MAX_SAFE_INTEGER);
}

function normalizeMethod<T extends string>(method: string, allowed: readonly T[], fallback: T): T {
  return allowed.includes(method as T) ? (method as T) : fallback;
}

function trimTrailingWhitespace(value: string): string {
  return value.replace(/\s+$/, '');
}

function parseStanzaDirective(networkInterface: DockerNetworkInterface, family: 'inet' | 'inet6', line: string) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) {
    if (trimmed.startsWith('#')) {
      const extras = family === 'inet' ? networkInterface.ipv4ExtraDirectives : networkInterface.ipv6ExtraDirectives;
      extras.push(line);
    }
    return;
  }

  const [directive = '', ...valueParts] = trimmed.split(/\s+/);
  const value = valueParts.join(' ');
  const extraDirectives =
    family === 'inet' ? networkInterface.ipv4ExtraDirectives : networkInterface.ipv6ExtraDirectives;

  if (family === 'inet') {
    switch (directive) {
      case 'address':
        networkInterface.ipv4Address = value;
        return;
      case 'netmask':
        networkInterface.netmask = value;
        return;
      case 'gateway':
        networkInterface.ipv4Gateway = value;
        return;
      case 'hostname':
        networkInterface.hostname = value;
        return;
      case 'dns-nameservers':
        networkInterface.dnsNameservers = value;
        return;
      case 'mtu':
        networkInterface.mtu = value;
        return;
    }
  } else {
    switch (directive) {
      case 'address': {
        const [address, prefix] = value.split('/');
        networkInterface.ipv6Address = address;
        if (prefix) networkInterface.prefixLength = prefix;
        return;
      }
      case 'netmask':
        networkInterface.prefixLength = value;
        return;
      case 'gateway':
        networkInterface.ipv6Gateway = value;
        return;
      case 'mtu':
        if (!networkInterface.mtu) networkInterface.mtu = value;
        return;
    }
  }

  extraDirectives.push(line);
}

/**
 * Parses the Debian ifupdown subset generated by the GNS3 Docker backend.
 * Comments, source statements, unrelated interfaces, and unsupported stanza
 * directives are retained so using the structured editor is not destructive.
 */
export function parseDockerNetworkConfiguration(
  configuration: string,
  adapterCount: number
): ParsedDockerNetworkConfiguration {
  const normalizedConfiguration = configuration.replace(/\r\n?/g, '\n');
  const lines = normalizedConfiguration.split('\n');
  const interfaces = new Map<string, DockerNetworkInterface>();
  const preservedLines: string[] = [];
  const getInterface = (name: string) => {
    if (!interfaces.has(name)) interfaces.set(name, createInterface(name));
    return interfaces.get(name)!;
  };

  let index = 0;
  while (index < lines.length) {
    const line = lines[index];
    if (COMMENTED_TEMPLATE_HEADER_PATTERN.test(line)) {
      index++;
      continue;
    }

    const commentedStartupMatch = line.match(COMMENTED_STARTUP_PATTERN);
    if (commentedStartupMatch) {
      const names = commentedStartupMatch[2].split(/\s+/);
      if (names.every((name) => INTERFACE_NAME_PATTERN.test(name))) {
        names.forEach((name) => getInterface(name));
        index++;
        continue;
      }
    }

    const commentedStanzaMatch = line.match(COMMENTED_STANZA_PATTERN);
    if (commentedStanzaMatch) {
      getInterface(commentedStanzaMatch[1]);
      index++;
      while (index < lines.length && COMMENTED_DIRECTIVE_PATTERN.test(lines[index])) {
        index++;
      }
      continue;
    }

    const startupMatch = line.match(/^(auto|allow-hotplug)\s+(.+?)\s*$/);
    if (startupMatch) {
      const keyword = startupMatch[1] as 'auto' | 'allow-hotplug';
      const names = startupMatch[2].split(/\s+/);
      const preservedNames: string[] = [];

      for (const name of names) {
        if (INTERFACE_NAME_PATTERN.test(name)) {
          const networkInterface = getInterface(name);
          networkInterface.enabled = true;
          networkInterface.startupKeyword = keyword;
        } else {
          preservedNames.push(name);
        }
      }

      if (preservedNames.length) preservedLines.push(`${keyword} ${preservedNames.join(' ')}`);
      index++;
      continue;
    }

    const stanzaMatch = line.match(/^iface\s+(\S+)\s+(inet6?|inet)\s+(\S+)\s*$/);
    if (!stanzaMatch) {
      preservedLines.push(line);
      index++;
      continue;
    }

    const [, name, family, method] = stanzaMatch;
    const stanzaLines = [line];
    index++;
    while (index < lines.length && (/^\s/.test(lines[index]) || /^\s*#/.test(lines[index]) || !lines[index])) {
      stanzaLines.push(lines[index]);
      index++;
    }

    if (!INTERFACE_NAME_PATTERN.test(name)) {
      preservedLines.push(...stanzaLines);
      continue;
    }

    const networkInterface = getInterface(name);
    networkInterface.enabled = true;
    if (family === 'inet') {
      networkInterface.ipv4Mode = normalizeMethod(method, ['dhcp', 'static', 'manual'] as const, 'manual');
    } else {
      networkInterface.ipv6Mode = normalizeMethod(method, ['auto', 'dhcp', 'static', 'manual'] as const, 'manual');
    }

    for (const directiveLine of stanzaLines.slice(1)) {
      parseStanzaDirective(networkInterface, family as 'inet' | 'inet6', directiveLine);
    }
  }

  const safeAdapterCount = Number.isFinite(adapterCount) ? Math.max(0, Math.floor(adapterCount)) : 0;
  for (let adapter = 0; adapter < safeAdapterCount; adapter++) {
    getInterface(`eth${adapter}`);
  }

  return {
    interfaces: [...interfaces.values()].sort(
      (left, right) => interfaceNumber(left.name) - interfaceNumber(right.name)
    ),
    preservedConfiguration: trimTrailingWhitespace(preservedLines.join('\n')),
  };
}

function appendDirective(lines: string[], name: string, value: string) {
  if (value.trim()) lines.push(`\t${name} ${value.trim()}`);
}

function appendExtraDirectives(lines: string[], directives: string[]) {
  for (const directive of directives) {
    if (!directive.trim()) continue;
    lines.push(/^\s/.test(directive) ? directive : `\t${directive}`);
  }
}

export function serializeDockerNetworkConfiguration(
  preservedConfiguration: string,
  interfaces: DockerNetworkInterface[]
): string {
  const generatedLines: string[] = [];

  for (const networkInterface of interfaces) {
    if (!networkInterface.enabled) continue;

    generatedLines.push(`${networkInterface.startupKeyword} ${networkInterface.name}`);
    generatedLines.push(`iface ${networkInterface.name} inet ${networkInterface.ipv4Mode}`);
    if (networkInterface.ipv4Mode === 'static') {
      appendDirective(generatedLines, 'address', networkInterface.ipv4Address);
      appendDirective(generatedLines, 'netmask', networkInterface.netmask);
      appendDirective(generatedLines, 'gateway', networkInterface.ipv4Gateway);
    }
    appendDirective(generatedLines, 'hostname', networkInterface.hostname);
    appendDirective(generatedLines, 'dns-nameservers', networkInterface.dnsNameservers);
    appendDirective(generatedLines, 'mtu', networkInterface.mtu);
    appendExtraDirectives(generatedLines, networkInterface.ipv4ExtraDirectives);

    if (networkInterface.ipv6Mode !== 'disabled') {
      generatedLines.push('');
      generatedLines.push(`iface ${networkInterface.name} inet6 ${networkInterface.ipv6Mode}`);
      if (networkInterface.ipv6Mode === 'static') {
        const address = networkInterface.ipv6Address.trim();
        const prefix = networkInterface.prefixLength.trim();
        appendDirective(generatedLines, 'address', address && prefix ? `${address}/${prefix}` : address);
        appendDirective(generatedLines, 'gateway', networkInterface.ipv6Gateway);
      }
      appendExtraDirectives(generatedLines, networkInterface.ipv6ExtraDirectives);
    }

    generatedLines.push('');
  }

  const sections = [
    trimTrailingWhitespace(preservedConfiguration),
    trimTrailingWhitespace(generatedLines.join('\n')),
  ].filter(Boolean);
  return sections.length ? `${sections.join('\n\n')}\n` : '';
}
